export const LOGIN_USER_START = 'LOGIN_USER_START'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const AUTH_USER_START = 'AUTH_USER_START'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL'
export const LOGOUT = 'LOGOUT'

export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'
