export const LOGIN_USER_START = 'LOGIN_USER_START'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const AUTH_USER_START = 'AUTH_USER_START'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL'
export const LOGOUT = 'LOGOUT'

export const CREATE_EVENT_START = 'CREATE_EVENT_START'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL'

export const REMOVE_EVENT_START = 'REMOVE_EVENT_START'
export const REMOVE_EVENT_SUCCESS = 'REMOVE_EVENT_SUCCESS'
export const REMOVE_EVENT_FAIL = 'REMOVE_EVENT_FAIL'

// UI
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'

export const SHOW_CREATE_EVENT_DIALOG = 'SHOW_CREATE_EVENT_DIALOG'
export const HIDE_CREATE_EVENT_DIALOG = 'HIDE_CREATE_EVENT_DIALOG'

export const SHOW_DELETE_EVENT_DIALOG = 'SHOW_DELETE_EVENT_DIALOG'
export const HIDE_DELETE_EVENT_DIALOG = 'HIDE_DELETE_EVENT_DIALOG'